kind: pipeline
type: docker
name: default

steps:
- name: check if event is tag
  image: alpine
  commands:
    - |
      if [ "$DRONE_BUILD_EVENT" != "tag" ]; then
        echo "This pipeline is only available for tags. Current event: $DRONE_BUILD_EVENT"
        exit 78
      fi

- name: build client app
  image: conneqthub/dotnet-maui-android
  commands:
  - cd mobile_apps/ClientApp
  - dotnet workload restore --download-to-cache --from-cache
  - dotnet workload install android --ignore-failed-sources
  - dotnet restore
  - dotnet publish -c Debug -f net9.0-android -o ./build

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key: 
      from_secret: gitea_api_key
    base_url: https://git.zmln.ru
    files: build/*