kind: pipeline
type: docker
name: default

steps:
- name: open directory project
  commands:
  - cd mobile_apps/ClientApp

- name: restote packages
  image: mcr.microsoft.com/dotnet/sdk:9.0
  commands:
  - dotnet restore

- name: build client app
  commands:
  - dotnet publish -c Release -f net9.0-android -o ./build