kind: pipeline
type: docker
name: default

steps:
- name: build client app
  image: mcr.microsoft.com/dotnet/sdk:9.0
  commands:
  - cd mobile_apps/ClientApp
  - dotnet workload restore
  - dotnet workload install android --ignore-failed-sources
  - dotnet restore
  - dotnet msbuild ./ClientApp.csproj -t:InstallAndroidDependencies -p:AndroidSdkDirectory=/opt/android-sdk -p:AcceptAndroidSDKLicenses=true
  - dotnet publish -c Release -p:AndroidSdkDirectory=/opt/android-sdk -f net9.0-android -o ./build