kind: pipeline
type: docker
name: default

steps:
- name: build client app
  image: windows-latest
  commands:
  - cd mobile_apps/ClientApp
  - dotnet workload install maui --ignore-failed-sources
  - dotnet restore
  - dotnet publish -c Release -f net9.0-android -o ./build