kind: pipeline
type: docker
name: default

steps:
- name: build client app
  image: conneqthub/dotnet-maui-android
  commands:
  - cd mobile_apps/ClientApp
  - dotnet workload restore
  - dotnet workload install android --ignore-failed-sources
  - dotnet restore
  - dotnet publish -c Debug -f net9.0-android -o ./build
- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key: 
      from_secret: gitea_api_key
    base_url: https://git.zmln.ru
    files: build/*