kind: pipeline
type: docker
name: default

steps:
- name: build client app
  image: mcr.microsoft.com/dotnet/sdk:9.0
  environment:
    NAME: Pop!_OS
    VERSION: 22.04 LTS
    ID: linux
    ID_LIKE: ubuntu debian
    PRETTY_NAME: Pop!_OS 22.04 LTS
    VERSION_ID: 22.04
  commands:
  - cd mobile_apps/ClientApp
  - dotnet workload install android --ignore-failed-sources
  - dotnet workload install ios --ignore-failed-sources
  - dotnet workload install maccatalyst --ignore-failed-sources
  - dotnet workload install maui --ignore-failed-sources
  - dotnet workload install maui-ios --ignore-failed-sources
  - dotnet workload install maui-maccatalyst --ignore-failed-sources
  - dotnet workload install maui-desktop --ignore-failed-sources
  - dotnet workload install maui-android --ignore-failed-sources
  - dotnet restore
  - dotnet publish -c Release -f net9.0-android -o ./build