kind: pipeline
type: docker
name: default

steps:
- name: build apps
  image: mcr.microsoft.com/dotnet/sdk:9.0
  commands:
  - cd mobile_apps/ClientApp
  - dotnet publish -c Release -f net9.0-android -o ./build